on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
      working-directory: ./test/bytewing-web
    - name: Build application
      run: npm run build
      working-directory: ./test/bytewing-web
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VM
      env:
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USERNAME: ${{ secrets.VM_USERNAME }}
        VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      run: |
        echo "$VM_SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        
        ssh -i id_rsa $VM_USERNAME@$VM_HOST "
          cd /home/app/test/bytewing-web
          git pull origin test
          npm install
          npm run build
          pm2 start test-ecosystem.config.cjs
        "
